### PR TITLE
Make snipets smaller, made it more portable and more fool-proof

### PR DESCRIPTION
**Pull request by TruncatedDinosour**

### CODE REVIEW

**Comment by TruncatedDinosour** [comment]
Joe,
I recommend you to
- use `main()` in bash and in general shell scripts
- use shellcheck
- use shfmt
- use `set -xe` instead of `echo`
- handle errors properly
- **not use BTRfs**

**Review by TruncatedDinosour — COMMENTED** [review]
Seems good :)

Can't see anything non-critical that would fail and cause
issues uwu

**Comment by killajoe** [comment]
Labai ačiū!

**Comment by killajoe** [comment]
> * not use BTRfs
yea i do not use it ;)

**Pull request merged**
